// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIre7oyjjpYG1-PCm7ArGCddZfI63LEu4',
    appId: '1:171137518707:android:3f7f704568b180c94b6e06',
    messagingSenderId: '171137518707',
    projectId: 'mechat-85e33',
    storageBucket: 'mechat-85e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMz-x9dvvfNPL4fLoHelEtbShwVERpFc',
    appId: '1:171137518707:ios:26c183a45b6cde7f4b6e06',
    messagingSenderId: '171137518707',
    projectId: 'mechat-85e33',
    storageBucket: 'mechat-85e33.appspot.com',
    androidClientId: '171137518707-5v2ke6kmq9i4b1h8ffqnmf5dim09ahb7.apps.googleusercontent.com',
    iosClientId: '171137518707-a1f915i8h58u1q3m0ba98ejckh690qfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
